import Layout from '@/components/layout';
import Head from 'next/head';
import Styles from '@/styles/aboutme.module.css';
import Image from 'next/image';
import { TOKEN, CAREER_DATABASE_ID } from '../config';

export default function Career({ projects }) {
    const imageSrc = projects.results[0].cover.file?.url || projects.results[0].cover.external.url

    return <>
        <Head>
            <title>Jeus portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <section className="text-gray-600 body-font mb-10">
                <div className="container px-5 py-10 mb-10 mx-auto flex flex-wrap">
                    <div className="lg:w-2/5 w-full mb-10 lg:mb-0 rounded-lg overflow-hidden">
                        <div className="rounded-lg h-100 overflow-hidden">
                            <Image
                                src={imageSrc}
                                width="100"
                                height="60"
                                layout="responsive"
                                objectFit='contain'
                                alt="Jeus"
                            />
                        </div>
                    </div>
                    <div className="flex flex-col flex-wrap lg:py-6 -mb-10 lg:w-1/2 lg:pl-12 lg:text-left text-center">
                        <div className="flex flex-col mb-2 lg:items-start items-center">
                            <li className={Styles.item}>
                                Name
                            </li>
                            <div className="flex-grow pl-11">
                                <p className="leading-relaxed text-base">JAEWOO KIM</p>
                            </div>
                        </div>
                        <div className="flex flex-col mb-2 lg:items-start items-center">
                            <li className={Styles.item}>
                                Birth
                            </li>
                            <div className="flex-grow pl-11">
                                <p className="leading-relaxed text-base">1989年生まれ</p>
                            </div>
                        </div>
                        <div className="flex flex-col mb-2 lg:items-start items-center">
                            <li className={Styles.item}>
                                City
                            </li>
                            <div className="flex-grow pl-11">
                                <p className="leading-relaxed text-base">Fukuoka, Japan</p>
                            </div>
                        </div>
                        <div className="flex flex-col mb-2 lg:items-start items-center">
                            <li className={Styles.item}>
                                e-mail
                            </li>
                            <div className="flex-grow pl-11">
                                <p className="leading-relaxed text-base">soyou30257@gmail.com</p>
                            </div>
                        </div>
                        <div className="flex flex-col mb-2 lg:items-start items-center">
                            <li className={Styles.item}>
                                Education
                            </li>
                            <div className="flex-grow pl-11">
                                <p className="leading-relaxed text-base">Busan University of Foreign Studies.</p>
                            </div>
                        </div>
                        <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-0 mt-10">Career</h1>
                        <div className="flex flex-col mb-2 lg:items-start items-center">
                            <div className={Styles.cbody}>
                                <div className={Styles.itemdiv}>
                                    <h5><b>富士ソフト株式会社</b></h5>
                                    <p>
                                        2017/1~現在
                                    </p>
                                    <br />
                                    ソフトウェアの開発・販売、システムインテグレーションなどを行う企業です。<br />
                                    <br />
                                    金融システム開発部署に所属し、クレジットカードシステム開発に携わっています。<br />
                                    2017/1から顧客のクレジットカードシステム開発に携わっており、<br />
                                    顧客のニアショア開発拠点（自社）にてWebAPI、Batch、社内Webサイトなど、主にサーバーサイド開発を行っています。<br />
                                    <br />
                                    <hr />
                                    <h3>カード基幹システム開発</h3>
                                    <h4>2017年 - 2020年</h4><br />
                                    <li>債権バッチシステム開発</li>
                                    <div class={Styles.sub}>
                                        IFRS（財務国際基準）対応
                                    </div>
                                    <li>請求バッチシステム開発</li>
                                    <div class={Styles.sub}>
                                        請求処理性能改善（処理時間短縮）
                                    </div>
                                    <li>少額保険システム開発</li>
                                    <div class={Styles.sub}>
                                        おすすめ保険リスト取得WebAPI開発<br />
                                        保険登録・削除API開発
                                    </div>

                                    <h3>Token管理中継サーバー開発</h3>
                                    <h4>2021年 - 2022年</h4><br />
                                    <li>カードブランド（VISA, MasterCard）との連携フロー理解</li>
                                    <div class={Styles.sub}>
                                        Token発行・更新・削除管理フロー<br />
                                        セキュリティ対策の理解（データ暗号化・複合化、証明書）
                                    </div>
                                    <li>基本設計・詳細設計</li>
                                    <div class={Styles.sub}>
                                        Kafkaを用いて処理分散を考慮した処理フロー設計<br />
                                        非同期処理によるステータス遷移問題を考慮した設計<br />
                                        大量データ処理Batch設計
                                    </div>
                                    <li>テックリーダー</li>
                                    <div class={Styles.sub}>
                                        開発関連知識共有<br />
                                        メンバー教育（JavaEE、Kubernetes、システム構成・フローなど）<br />
                                        コードレビュー担当<br />
                                    </div>
                                    <li>負荷性能試験によるPayara web server、Kubernetes POD チューニング</li>
                                    <li>Real環境障害発生時の対処手順作成</li>
                                    <div class={Styles.sub}>
                                        原因調査手順・原因判断ポイント作成<br />
                                        データリカバリ手順・Tool作成<br />
                                        報告ルート確認と判断基準作成
                                    </div>

                                    <h3>社内メンテナンス用Webサイト開発</h3>
                                    <h4>2023年 - 現在</h4><br />
                                    <li>要件整理・調整</li>
                                    <div class={Styles.sub}>
                                        企画部署とコミュニケーションをとり、<br />
                                        実現可能性を考慮した機能を調整・提案することで要件を整理
                                    </div>
                                    <li>基本設計・詳細設計</li>
                                    <li>テックリーダー</li>
                                    <div class={Styles.sub}>
                                        開発関連知識共有<br />
                                        コードレビュー担当<br />
                                        開発タスク整理と割当て、進捗確認
                                        外国籍チームとのコミュニケーションロース対策検討<br />
                                    </div>
                                    <li>JSF開発の理解</li>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </Layout>
    </>
}

export async function getStaticProps() {
    const options = {
        method: 'POST',
        headers: {
            accept: 'application/json',
            'Notion-Version': '2022-06-28',
            'content-type': 'application/json',
            Authorization: `Bearer ${TOKEN}`
        },
        body: JSON.stringify({ page_size: 100 })
    };

    const res = await fetch(`https://api.notion.com/v1/databases/${CAREER_DATABASE_ID}/query`, options);
    const projects = await res.json();

    return {
        props: { projects }, // will be passed to the page component as props
    }
}