import Head from 'next/head'
import Layout from '@/components/layout';
import React from 'react'
import Lottie from 'react-lottie-player'
import lottieJson from '/public/contact-animate.json'

export default function ContactMe() {
    return (
        <div>
            <Layout>
                <Head>
                    <title>Jeus portfolio</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
                    <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
                        <div className="lg:max-w-[40%] lg:w-full md:w-1/2 w-5/6">
                            <Lottie
                                loop
                                animationData={lottieJson}
                                play
                            />
                        </div>
                        <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
                            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Contact me !
                                <br className="hidden lg:inline-block" />
                            </h1>
                            <p className="mb-8 leading-relaxed">e-mail : soyou30257@gmail.com</p>
                        </div>
                    </div>
                </section>
            </Layout>
        </div>
    )
}