import Layout from '@/components/layout';
import Head from 'next/head';
import { TOKEN, DATABASE_ID } from '../config';

export default function Projects({projects}) {
    return (
        <>
            <Head>
                <title>Jeus portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <h1>Projectの数： {projects.results.length} </h1>
                {projects.results.map((aProject) => (
                    <h1>{aProject.properties.Name.title[0].plain_text}</h1>
                ))}
            </Layout>
        </>
    );
}

export async function getStaticProps() {
    const options = {
        method: 'POST',
        headers: {
          accept: 'application/json',
          'Notion-Version': '2022-06-28',
          'content-type': 'application/json',
          Authorization: `Bearer ${TOKEN}`
        },
        body: JSON.stringify({page_size: 100})
      };
      
      const res = await fetch(`https://api.notion.com/v1/databases/${DATABASE_ID}/query`, options);
      const projects = await res.json();

    return {
        props: {projects}, // will be passed to the page component as props
    }
}