import Layout from '@/components/layout';
import Head from 'next/head';

export default function Projects() {
    return (
        <>
            <Head>
                <title>Jeus portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <h1>Project</h1>
            </Layout>
        </>
    );
}